(ns flashcards.db)

(def default-db
  {:static {:name "Flashcards"
            :version "0.0.1"
            :valid-options {:direction [:new-to-known :known-to-new :both]
                            :show-choices [true false]
                            :num-choices (range 2 10)}}
   :options {:direction :both
             :num-choices 4
             :show-choices true}
   :dynamic {:word "?"
             :translation "?"
             :translation-choices (mapv (partial str "?") (range 10))
             }
   :dictionary {"من" "of"
                "و" "and"
                "إلى" "to"
                "في" "in"
                "أنت" "you"
                "أن" "that"
                "هو" "he"
                "كان" "was"
                "كما" "as"
                "مع" "with"
                "له" "his"
                "هم" "they"
                "أنا" "I"
                "يكون" "be"
                "هذا" "this"
                "لديك" "have"
                "أو" "or"
                "واحد" "one"
                "من قبل" "by"
                "كلمة" "word"
                "لكن" "but"
                "ليس" "not"
                "ما" "what"
                "كل" "all"
                "كانت" "were"
                "نحن" "we"
                "عندما" "when"
                "ك" "your"
                "تمكن" "can"
                "قال" "said"
                "هناك" "there"
                "استخدم" "use"
                "كل واحد" "each"
                "التي" "which"
                "هي" "she"
                "فعل" "do"
                "كيف" "how"
                "إذا" "if"
                "سوف" "will"
                "فوق" "up"
                "آخر" "other"
                "عن" "about"
                "خارج" "out"
                "داخل" "inside"
                "كثير" "many"
                "ثم" "then"
                "هن" "them"
                "هؤلاء" "these"
                "هكذا" "so"
                "بعض" "some"
                "لها" "her"
                "أراد" "would"
                "جعل" "make"
                "مثل" "like"
                "وقت" "time"
                "لديه" "has"
                "بحث" "look"
                "اثنان" "two"
                "أكثر" "more"
                "كتب" "write"
                "ذهب" "go"
                "رأى" "see"
                "رقم" "number"
                "لا" "no"
                "نعم" "yes"
                "طريق" "way"
                "يمكن" "could"
                "الناس" "people"
                "لي" "my"
                "غير" "than"
                "الأول" "first"
                "ماء" "water"
                "استدعاء" "call"
                "الذي" "who"
                "نفط" "oil"
                "الآن" "now"
                "اكتشاف" "find"
                "طويل" "long"
                "قصير" "short"
                "يوم" "day"
                "الحصول على" "get"
                "جاء" "come"
                "مصنوع" "made"
                "قد" "may"
                "جزء" "part"
                "يضحك" "laugh"
                "جيد" "good"
                "جميل" "beautiful"
                "قبيح" "ugly"
                "صعب" "difficult"
                "سهل" "easy"
                "سييء" "bad"
                "صباح" "morning"
                "مساء" "evening"
                "لذيذة" "delicious"
                "قهوة" "coffee"
                "شاي" "tea"
                "دجاج" "chicken"
                "سمك" "fish"
                "لحم بقر" "beef"
                }})
